import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import {
  Code2,
  Shield,
  FileSearch,
  Zap,
  GitBranch,
  BarChart3,
  Download,
  ChevronRight,
  ArrowRight,
  CheckCircle2,
  ChevronDown,
} from "lucide-react";
import { useState } from "react";
import { useScrollAnimation } from "@/hooks/use-scroll-animation";

function FAQItem({ question, answer }: { question: string; answer: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border-b border-border last:border-0">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between gap-4 py-5 text-left hover-elevate rounded-lg px-2"
        data-testid={`button-faq-${question.slice(0, 20).replace(/\s/g, "-").toLowerCase()}`}
      >
        <span className="font-medium text-foreground">{question}</span>
        <ChevronDown
          className={`w-5 h-5 text-muted-foreground shrink-0 transition-transform duration-200 ${open ? "rotate-180" : ""}`}
        />
      </button>
      <div
        className="overflow-hidden transition-all duration-200"
        style={{ maxHeight: open ? "200px" : "0px", opacity: open ? 1 : 0 }}
      >
        <div className="px-2 pb-5 text-muted-foreground text-sm leading-relaxed" data-testid={`text-faq-answer-${question.slice(0, 15).replace(/\s/g, "-").toLowerCase()}`}>
          {answer}
        </div>
      </div>
    </div>
  );
}

export default function GHPagesLandingPage() {
  const APP_URL = import.meta.env.VITE_APP_URL || "#";
  useScrollAnimation();

  const features = [
    {
      icon: Shield,
      title: "Security Scanning",
      desc: "Detect vulnerabilities, exposed secrets, and unsafe patterns in your codebase before they become problems.",
    },
    {
      icon: FileSearch,
      title: "Technical Debt Analysis",
      desc: "Identify code smells, complexity hotspots, and maintenance risks across your entire repository.",
    },
    {
      icon: Code2,
      title: "Documentation Quality",
      desc: "Evaluate comment coverage, code clarity, and documentation gaps that slow down your team.",
    },
    {
      icon: BarChart3,
      title: "Visual Dashboards",
      desc: "Track code health over time with score rings, trend charts, and detailed file-level breakdowns.",
    },
    {
      icon: Download,
      title: "Export Reports",
      desc: "Generate standalone HTML reports you can share with your team or deploy to GitHub Pages.",
    },
    {
      icon: Zap,
      title: "Fast AI Analysis",
      desc: "Get results in seconds. Our multi-agent AI scans files concurrently for rapid, thorough analysis.",
    },
  ];

  const steps = [
    {
      num: "1",
      title: "Connect Your Repo",
      desc: "Paste any public GitHub repository URL to get started.",
    },
    {
      num: "2",
      title: "Run a Scan",
      desc: "Our AI agents analyze your code for security, debt, and documentation quality.",
    },
    {
      num: "3",
      title: "Review Results",
      desc: "Explore detailed scores, issue breakdowns, and AI-suggested improvements.",
    },
  ];

  const faqs = [
    {
      q: "Is Vanguard AI free to use?",
      a: "Yes, you can sign up and start scanning repositories at no cost. We use AI credits to power the analysis, so there may be usage limits depending on your plan.",
    },
    {
      q: "Does it work with private repositories?",
      a: "Currently, Vanguard AI supports public GitHub repositories. Private repo support is on our roadmap for a future release.",
    },
    {
      q: "What languages are supported?",
      a: "We analyze TypeScript, JavaScript, Python, Go, Rust, Java, C, C++, and more. The AI understands language-specific patterns and best practices for each.",
    },
    {
      q: "How long does a scan take?",
      a: "Most scans complete in under 15 seconds. We analyze up to 5 key files per scan using concurrent AI agents for maximum speed.",
    },
    {
      q: "Can I export and share reports?",
      a: "Absolutely. Every scan can be exported as a standalone HTML file that you can share with your team, attach to PRs, or deploy to GitHub Pages.",
    },
    {
      q: "How are the scores calculated?",
      a: "Each file receives three scores (0-100) for security, technical debt, and documentation quality. These are generated by AI analysis considering industry best practices, common vulnerability patterns, and code quality standards.",
    },
  ];

  return (
    <div className="min-h-screen bg-background flex flex-col dark">
      <nav className="sticky top-0 z-[999] border-b border-border bg-background/80 backdrop-blur-lg">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between gap-4">
          <a href="#" className="flex items-center gap-2.5" data-testid="link-landing-brand">
            <div className="bg-primary/20 p-1.5 rounded-lg">
              <Code2 className="w-5 h-5 text-primary" />
            </div>
            <span className="font-bold text-lg tracking-tight" data-testid="text-landing-brand">
              Vanguard AI
            </span>
          </a>
          <div className="flex items-center gap-3 flex-wrap">
            <a href={APP_URL}>
              <Button variant="ghost" data-testid="button-landing-login">
                Log In
              </Button>
            </a>
            <a href={APP_URL}>
              <Button data-testid="button-landing-signup">Sign Up</Button>
            </a>
          </div>
        </div>
      </nav>

      <section className="relative overflow-hidden">
        <div className="absolute inset-0 pointer-events-none">
          <div className="absolute top-20 left-1/4 w-[500px] h-[500px] bg-primary/8 rounded-full blur-3xl animate-float" />
          <div className="absolute bottom-10 right-1/4 w-[400px] h-[400px] bg-primary/5 rounded-full blur-3xl animate-float-delayed" />
        </div>
        <div className="max-w-6xl mx-auto px-6 pt-24 pb-20 text-center relative z-10">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-primary/20 bg-primary/5 text-primary text-sm font-medium mb-8 animate-fade-in-down">
            <Zap className="w-3.5 h-3.5" />
            AI-Powered Code Intelligence
          </div>
          <h1
            className="text-4xl sm:text-5xl md:text-6xl font-bold tracking-tight leading-tight mb-6 animate-fade-in-up"
            data-testid="text-hero-title"
          >
            Know the health of
            <br />
            <span className="text-primary animate-glow">your codebase</span>
          </h1>
          <p className="text-lg sm:text-xl text-muted-foreground max-w-2xl mx-auto mb-10 leading-relaxed animate-fade-in-up animation-delay-200">
            Vanguard AI scans your GitHub repositories for security
            vulnerabilities, technical debt, and documentation gaps — then gives
            you clear scores, actionable insights, and AI-suggested fixes.
          </p>
          <div className="flex items-center justify-center gap-4 flex-wrap animate-fade-in-up animation-delay-400">
            <a href={APP_URL}>
              <Button size="lg" className="gap-2 text-base" data-testid="button-hero-cta">
                Get Started Free
                <ArrowRight className="w-4 h-4" />
              </Button>
            </a>
            <a href="#how-it-works">
              <Button variant="outline" size="lg" className="gap-2 text-base" data-testid="button-hero-learn">
                How It Works
                <ChevronRight className="w-4 h-4" />
              </Button>
            </a>
          </div>

          <div className="mt-16 grid grid-cols-3 gap-6 max-w-lg mx-auto text-center animate-fade-in-up animation-delay-600">
            {[
              { val: "< 15s", label: "Scan Time" },
              { val: "10+", label: "Languages" },
              { val: "3", label: "Score Categories" },
            ].map((s) => (
              <div key={s.label} data-testid={`text-stat-${s.label.replace(/\s/g, "-").toLowerCase()}`}>
                <p className="text-2xl font-bold text-primary">{s.val}</p>
                <p className="text-xs text-muted-foreground mt-1">{s.label}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 border-t border-border" id="features">
        <div className="max-w-6xl mx-auto px-6">
          <div className="text-center mb-14">
            <h2 className="text-3xl font-bold mb-3 scroll-animate" data-testid="text-features-title">
              Everything you need to ship healthier code
            </h2>
            <p className="text-muted-foreground max-w-xl mx-auto scroll-animate">
              One platform to analyze, track, and improve the quality of every
              repository you manage.
            </p>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5">
            {features.map((f, i) => (
              <Card key={f.title} className="hover-elevate transition-all duration-200 scroll-animate" style={{ animationDelay: `${i * 100}ms` }}>
                <CardContent className="p-6">
                  <div className="bg-primary/10 w-10 h-10 rounded-lg flex items-center justify-center mb-4">
                    <f.icon className="w-5 h-5 text-primary" />
                  </div>
                  <h3 className="font-semibold mb-2" data-testid={`text-feature-${f.title.replace(/\s/g, "-").toLowerCase()}`}>
                    {f.title}
                  </h3>
                  <p className="text-sm text-muted-foreground leading-relaxed">
                    {f.desc}
                  </p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 border-t border-border bg-card/30" id="how-it-works">
        <div className="max-w-6xl mx-auto px-6">
          <div className="text-center mb-14">
            <h2 className="text-3xl font-bold mb-3 scroll-animate" data-testid="text-how-title">
              How it works
            </h2>
            <p className="text-muted-foreground max-w-xl mx-auto scroll-animate">
              Get from repository URL to actionable insights in three simple
              steps.
            </p>
          </div>
          <div className="grid md:grid-cols-3 gap-8 max-w-4xl mx-auto">
            {steps.map((s, i) => (
              <div key={s.num} className="text-center scroll-animate" style={{ animationDelay: `${i * 150}ms` }}>
                <div className="w-12 h-12 rounded-full bg-primary text-primary-foreground font-bold text-xl flex items-center justify-center mx-auto mb-5">
                  {s.num}
                </div>
                <h3 className="font-semibold text-lg mb-2">{s.title}</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  {s.desc}
                </p>
              </div>
            ))}
          </div>
          <div className="text-center mt-12 scroll-animate">
            <a href={APP_URL}>
              <Button size="lg" className="gap-2" data-testid="button-how-cta">
                Get Started Free
                <ArrowRight className="w-4 h-4" />
              </Button>
            </a>
          </div>
        </div>
      </section>

      <section className="py-20 border-t border-border" id="why">
        <div className="max-w-6xl mx-auto px-6">
          <div className="text-center mb-14">
            <h2 className="text-3xl font-bold mb-3 scroll-animate">
              Why teams choose Vanguard AI
            </h2>
            <p className="text-muted-foreground max-w-xl mx-auto scroll-animate">
              Built for developers who care about code quality but don't have
              hours to spend reviewing every file.
            </p>
          </div>
          <div className="grid sm:grid-cols-2 gap-5 max-w-3xl mx-auto">
            {[
              "Instant visibility into code health across all your repos",
              "Catch security risks before they reach production",
              "Track technical debt trends over time with scan history",
              "Share professional reports with stakeholders in one click",
              "AI-powered suggestions that go beyond linting rules",
              "No complex setup required — just paste a GitHub URL",
            ].map((item, i) => (
              <div key={item} className="flex items-start gap-3 scroll-animate" style={{ animationDelay: `${i * 80}ms` }}>
                <CheckCircle2 className="w-5 h-5 text-primary shrink-0 mt-0.5" />
                <span className="text-sm text-muted-foreground">{item}</span>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 border-t border-border bg-card/30" id="faq">
        <div className="max-w-2xl mx-auto px-6">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold mb-3 scroll-animate" data-testid="text-faq-title">
              Frequently Asked Questions
            </h2>
          </div>
          <div className="scroll-animate">
            {faqs.map((f) => (
              <FAQItem key={f.q} question={f.q} answer={f.a} />
            ))}
          </div>
        </div>
      </section>

      <section className="py-20 border-t border-border">
        <div className="max-w-3xl mx-auto px-6 text-center">
          <div className="bg-primary/5 border border-primary/10 rounded-xl p-10 scroll-animate">
            <GitBranch className="w-10 h-10 text-primary mx-auto mb-4" />
            <h2 className="text-2xl font-bold mb-3">
              Ready to improve your code health?
            </h2>
            <p className="text-muted-foreground mb-8 max-w-md mx-auto">
              Connect your first repository and get a full analysis in under 15
              seconds. No credit card required.
            </p>
            <a href={APP_URL}>
              <Button size="lg" className="gap-2 text-base" data-testid="button-cta-bottom">
                Get Started Free
                <ArrowRight className="w-4 h-4" />
              </Button>
            </a>
          </div>
        </div>
      </section>

      <footer className="border-t border-border py-10 bg-card/20">
        <div className="max-w-6xl mx-auto px-6">
          <div className="flex flex-col sm:flex-row items-center justify-between gap-6">
            <div className="flex items-center gap-2.5">
              <div className="bg-primary/20 p-1.5 rounded-lg">
                <Code2 className="w-4 h-4 text-primary" />
              </div>
              <span className="font-semibold" data-testid="text-footer-brand">
                Vanguard AI
              </span>
            </div>
            <div className="flex items-center gap-6 text-sm text-muted-foreground flex-wrap justify-center">
              <a href="#features" className="hover:text-foreground transition-colors" data-testid="link-footer-features">
                Features
              </a>
              <a href="#how-it-works" className="hover:text-foreground transition-colors" data-testid="link-footer-how">
                How It Works
              </a>
              <a href="#faq" className="hover:text-foreground transition-colors" data-testid="link-footer-faq">
                FAQ
              </a>
              <a href={APP_URL} className="hover:text-foreground transition-colors" data-testid="link-footer-login">
                Log In
              </a>
            </div>
          </div>
          <div className="mt-8 pt-6 border-t border-border text-center text-xs text-muted-foreground">
            &copy; {new Date().getFullYear()} Vanguard AI. All rights reserved.
          </div>
        </div>
      </footer>
    </div>
  );
}
