import type { Scan, FileAnalysis, Repository } from "@shared/schema";

interface ExportData {
  repo: Repository;
  scan: Scan;
  files: FileAnalysis[];
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

function getScoreColor(score: number | null): string {
  if (!score) return "#6b7280";
  if (score >= 80) return "#22c55e";
  if (score >= 50) return "#eab308";
  return "#ef4444";
}

function getSeverityColor(severity: string): string {
  if (severity === "high") return "#ef4444";
  if (severity === "medium") return "#eab308";
  return "#3b82f6";
}

export function generateGitHubPagesReport(data: ExportData): string {
  const { repo, scan, files } = data;
  const scanDate = scan.createdAt ? new Date(scan.createdAt).toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric", hour: "2-digit", minute: "2-digit"
  }) : "Unknown";

  const filesHtml = files.map((file, idx) => {
    const issues = (file.issues as any[]) || [];
    const issuesHtml = issues.map(issue => `
      <div class="issue">
        <div class="issue-header">
          <span class="issue-badge" style="background:${getSeverityColor(issue.severity)}20;color:${getSeverityColor(issue.severity)};border:1px solid ${getSeverityColor(issue.severity)}30">
            ${escapeHtml(issue.type)} - ${escapeHtml(issue.severity)}
          </span>
          ${issue.line ? `<span class="issue-line">Line ${issue.line}</span>` : ""}
        </div>
        <p class="issue-desc">${escapeHtml(issue.description)}</p>
        ${issue.suggestion ? `<div class="issue-suggestion">${escapeHtml(issue.suggestion)}</div>` : ""}
      </div>
    `).join("");

    return `
      <div class="file-card" id="file-${idx}">
        <div class="file-header" onclick="toggleFile(${idx})">
          <div class="file-info">
            <svg class="file-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/></svg>
            <span class="file-path">${escapeHtml(file.filePath)}</span>
            <span class="file-lang">${escapeHtml(file.language || "text")}</span>
          </div>
          <div class="file-scores">
            <span class="mini-score" style="color:${getScoreColor(file.technicalDebtScore)}">Debt: ${file.technicalDebtScore ?? "-"}</span>
            <span class="mini-score" style="color:${getScoreColor(file.securityScore)}">Security: ${file.securityScore ?? "-"}</span>
            <span class="mini-score" style="color:${getScoreColor(file.documentationScore)}">Docs: ${file.documentationScore ?? "-"}</span>
            <svg class="chevron" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="6 9 12 15 18 9"/></svg>
          </div>
        </div>
        <div class="file-body" id="file-body-${idx}" style="display:none">
          ${issues.length > 0 ? `<div class="issues-section"><h4>Issues (${issues.length})</h4>${issuesHtml}</div>` : '<div class="no-issues">No issues detected</div>'}
          ${file.originalCode || file.refactoredCode ? `
          <div class="diff-section">
            <div class="diff-grid">
              <div class="diff-pane">
                <div class="diff-label original-label">Original</div>
                <pre class="diff-code original-code">${escapeHtml(file.originalCode || "// No original content")}</pre>
              </div>
              <div class="diff-pane">
                <div class="diff-label optimized-label">Vanguard AI Optimized</div>
                <pre class="diff-code optimized-code">${escapeHtml(file.refactoredCode || "// No suggested changes")}</pre>
              </div>
            </div>
          </div>` : ""}
        </div>
      </div>
    `;
  }).join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Vanguard AI Report - ${escapeHtml(repo.owner)}/${escapeHtml(repo.name)}</title>
<meta name="description" content="Code intelligence report for ${escapeHtml(repo.owner)}/${escapeHtml(repo.name)} generated by Vanguard AI">
<meta name="generator" content="Vanguard AI Code Intelligence Platform">
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:'Inter',-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:#0f172a;color:#e2e8f0;line-height:1.6}
a{color:#3b82f6;text-decoration:none}
a:hover{text-decoration:underline}
.container{max-width:1200px;margin:0 auto;padding:0 1.5rem}
header{border-bottom:1px solid #1e293b;padding:1rem 0;position:sticky;top:0;background:#0f172aee;backdrop-filter:blur(12px);z-index:50}
.header-inner{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:1rem}
.brand{display:flex;align-items:center;gap:0.5rem;font-size:1.25rem;font-weight:700}
.brand-icon{background:#3b82f620;padding:0.4rem;border-radius:0.5rem;display:flex}
.brand-icon svg{width:1.25rem;height:1.25rem;color:#3b82f6}
.meta{font-size:0.875rem;color:#94a3b8}
.hero{padding:3rem 0;border-bottom:1px solid #1e293b}
.hero h1{font-size:2rem;font-weight:700;margin-bottom:0.5rem;letter-spacing:-0.025em}
.hero .repo-link{color:#94a3b8;font-size:0.875rem;display:flex;align-items:center;gap:0.5rem;margin-bottom:1.5rem}
.scores-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:1rem;margin-top:1.5rem}
.score-card{background:#1e293b;border:1px solid #334155;border-radius:0.75rem;padding:1.25rem;text-align:center}
.score-card .score-value{font-size:2.5rem;font-weight:800;letter-spacing:-0.05em}
.score-card .score-label{font-size:0.75rem;text-transform:uppercase;letter-spacing:0.1em;color:#94a3b8;margin-top:0.25rem}
.summary-section{padding:2rem 0;border-bottom:1px solid #1e293b}
.summary-section h2{font-size:1.25rem;font-weight:600;margin-bottom:0.75rem}
.summary-text{color:#94a3b8;font-size:0.95rem}
.files-section{padding:2rem 0}
.files-section h2{font-size:1.25rem;font-weight:600;margin-bottom:1rem}
.file-card{background:#1e293b;border:1px solid #334155;border-radius:0.75rem;margin-bottom:0.75rem;overflow:hidden}
.file-header{display:flex;align-items:center;justify-content:space-between;padding:1rem 1.25rem;cursor:pointer;transition:background 0.15s;flex-wrap:wrap;gap:0.5rem}
.file-header:hover{background:#334155}
.file-info{display:flex;align-items:center;gap:0.5rem;flex-wrap:wrap}
.file-icon{width:1rem;height:1rem;color:#94a3b8;flex-shrink:0}
.file-path{font-family:'JetBrains Mono',monospace;font-size:0.875rem;font-weight:500}
.file-lang{font-size:0.7rem;background:#0f172a;padding:0.125rem 0.5rem;border-radius:0.25rem;border:1px solid #334155;color:#94a3b8}
.file-scores{display:flex;align-items:center;gap:1rem;flex-wrap:wrap}
.mini-score{font-size:0.75rem;font-weight:600}
.chevron{width:1rem;height:1rem;color:#94a3b8;transition:transform 0.2s}
.file-card.open .chevron{transform:rotate(180deg)}
.file-body{border-top:1px solid #334155}
.issues-section{padding:1.25rem}
.issues-section h4{font-size:0.875rem;font-weight:600;margin-bottom:0.75rem;color:#94a3b8}
.issue{background:#0f172a;border:1px solid #334155;border-radius:0.5rem;padding:1rem;margin-bottom:0.75rem}
.issue-header{display:flex;align-items:center;gap:0.5rem;margin-bottom:0.5rem;flex-wrap:wrap}
.issue-badge{font-size:0.65rem;padding:0.125rem 0.5rem;border-radius:0.25rem;text-transform:uppercase;font-weight:600;letter-spacing:0.05em}
.issue-line{font-size:0.7rem;color:#64748b;font-family:monospace}
.issue-desc{font-size:0.875rem;font-weight:500}
.issue-suggestion{font-size:0.8rem;color:#94a3b8;background:#1e293b;padding:0.5rem;border-radius:0.375rem;margin-top:0.5rem}
.no-issues{padding:1.25rem;color:#22c55e;font-size:0.875rem;display:flex;align-items:center;gap:0.5rem}
.diff-section{border-top:1px solid #334155}
.diff-grid{display:grid;grid-template-columns:1fr 1fr}
@media(max-width:768px){.diff-grid{grid-template-columns:1fr}}
.diff-pane{overflow:hidden}
.diff-label{padding:0.5rem 1rem;font-size:0.75rem;font-weight:600;text-transform:uppercase;letter-spacing:0.1em;border-bottom:1px solid #334155}
.original-label{color:#fca5a5;background:#7f1d1d10}
.optimized-label{color:#86efac;background:#14532d10}
.diff-code{padding:1rem;font-family:'JetBrains Mono',monospace;font-size:0.75rem;line-height:1.7;overflow-x:auto;white-space:pre-wrap;max-height:500px;overflow-y:auto}
.original-code{color:#fca5a590;background:#7f1d1d08}
.optimized-code{color:#86efacdd;background:#14532d08}
footer{border-top:1px solid #1e293b;padding:2rem 0;text-align:center;color:#64748b;font-size:0.8rem}
.status-badge{display:inline-block;padding:0.25rem 0.75rem;border-radius:9999px;font-size:0.75rem;font-weight:600;text-transform:capitalize}
.status-completed{background:#14532d;color:#86efac}
.status-failed{background:#7f1d1d;color:#fca5a5}
.status-processing{background:#78350f;color:#fde68a}
</style>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600&display=swap" rel="stylesheet">
</head>
<body>
<header>
  <div class="container header-inner">
    <div class="brand">
      <div class="brand-icon">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M17 6.1H3"/><path d="m21 12.1-4-4 4-4"/><path d="M17 17.9H3"/><path d="m21 17.9-4-4"/></svg>
      </div>
      Vanguard AI
    </div>
    <div class="meta">Generated ${escapeHtml(scanDate)}</div>
  </div>
</header>

<div class="container">
  <div class="hero">
    <h1>${escapeHtml(repo.owner)}/${escapeHtml(repo.name)}</h1>
    <div class="repo-link">
      <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"/></svg>
      <a href="${escapeHtml(repo.url)}" target="_blank" rel="noreferrer">${escapeHtml(repo.url)}</a>
    </div>
    <span class="status-badge status-${scan.status}">${escapeHtml(scan.status)}</span>
    <div class="scores-grid">
      <div class="score-card">
        <div class="score-value" style="color:${getScoreColor(scan.overallScore)}">${scan.overallScore ?? "-"}</div>
        <div class="score-label">Overall</div>
      </div>
      <div class="score-card">
        <div class="score-value" style="color:${getScoreColor(scan.technicalDebtScore)}">${scan.technicalDebtScore ?? "-"}</div>
        <div class="score-label">Tech Debt</div>
      </div>
      <div class="score-card">
        <div class="score-value" style="color:${getScoreColor(scan.securityScore)}">${scan.securityScore ?? "-"}</div>
        <div class="score-label">Security</div>
      </div>
      <div class="score-card">
        <div class="score-value" style="color:${getScoreColor(scan.documentationScore)}">${scan.documentationScore ?? "-"}</div>
        <div class="score-label">Documentation</div>
      </div>
    </div>
  </div>

  <div class="summary-section">
    <h2>Summary</h2>
    <p class="summary-text">${escapeHtml(scan.summary || "No summary available.")}</p>
  </div>

  <div class="files-section">
    <h2>Analyzed Files (${files.length})</h2>
    ${filesHtml}
  </div>
</div>

<footer>
  <div class="container">
    <p>&copy; ${new Date().getFullYear()} Vanguard AI Code Intelligence Platform. Report generated for ${escapeHtml(repo.owner)}/${escapeHtml(repo.name)}.</p>
  </div>
</footer>

<script>
function toggleFile(idx){
  var card=document.getElementById('file-'+idx);
  var body=document.getElementById('file-body-'+idx);
  if(body.style.display==='none'){body.style.display='block';card.classList.add('open')}
  else{body.style.display='none';card.classList.remove('open')}
}
</script>
</body>
</html>`;
}
